name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/jdx/mise:2026.8.7
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - run: |
          mise trust
          mise deps
          mise run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
